parameters:
  name: ''
  displayName: ''
  gfxapi: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
  steps:
  - checkout: self
    submodules: recursive
  - script: |
      curl -O https://www.libsdl.org/release/SDL2-2.0.10.dmg
      /usr/bin/hdiutil attach -noverify -noautoopen SDL2-2.0.10.dmg
      sudo cp -af /Volumes/SDL2/SDL2.framework /Library/Frameworks/
      curl -sL "https://github.com/zellski/FBXSDK-Darwin/archive/2019.2.tar.gz" | tar xz --strip-components=1 --include */sdk/
      brew install zstd
      zstd -d -r --rm sdk
    displayName: 'Install dependencies'
  - template: azure-pipelines-steps-linkedvdk.yml
  - script: 3rdParty/udcore/bin/premake-bin/premake5-osx xcode4 --gfxapi=${{ parameters.gfxapi }} --fbxsdk=$(Build.SourcesDirectory)/sdk/Darwin/2019.2
    displayName: 'Run Premake'
  - task: Xcode@5
    displayName: 'Build Projects'
    inputs:
      xcWorkspacePath: 'udStream.xcodeproj'
      sdk: 'macosx'
      configuration: $(configuration)
      packageApp: false
  - task: Xcode@5
    displayName: 'Build Projects'
    inputs:
      xcWorkspacePath: 'vcTesting/vcTesting.xcodeproj'
      sdk: 'macosx'
      configuration: $(configuration)
      packageApp: false
  - script: builds/tests/vcTesting --gtest_shuffle --gtest_output=xml
    displayName: 'Run Tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test_detail.xml'
      testRunTitle: ${{ parameters.name }}_$(platform)_$(configuration)
  - script: buildscripts/macos-package.sh create
  - script: buildscripts/macos-package.sh
  - publish: builds/udStream.dmg
    displayName: 'Publish Artifacts'
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))
    artifact: ${{ parameters.name }}$(configuration)
